### ISSUE TITLE
Filters & MT Routes are not visible after creating online in JCLI

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin-web#9]
Hi 
I created filters and MT ROUTERS from Online API but it is not visible in JCLI. Later On i changed source code and ran "Persist"after command executes from API . then it started  being visible in JCLI. 

Please advise. is this correct way or i am missing something.

**Comment by farirat** [comment]
filters and http connectors are just helpers, they are not persisted till you do it manually, as for mt routes, they are shared between sessions, so when you create one from a third party api you'll find it in any other jcli session with no need to persist.

**Comment by sah-anshu** [comment]
Ok. In that case executing persist is mandatory via web-api.
Pl correct me if i am wrong.

**Comment by farirat** [comment]
Yes
